insert into public.mb_challenges (id,category,level,minutes,title,body,goal_tags,active,approved_version) values
('agua_01','hidratacao',1,1,'Primeiro copo do dia','Beba um copo de água depois de acordar ou junto da primeira refeição.',array['energia','rotina','consistencia'],true,1),
('agua_02','hidratacao',1,1,'Água à vista','Deixe sua garrafa ou copo em um lugar visível durante a próxima parte do dia.',array['rotina','consistencia'],true,1),
('agua_03','hidratacao',2,2,'Duas pausas de hidratação','Escolha dois momentos do seu dia para fazer uma pausa curta e beber água.',array['energia','consistencia'],true,1),
('agua_04','hidratacao',3,3,'Planeje sua hidratação','Defina três momentos do dia em que você vai lembrar de beber água e marque quando cumprir.',array['rotina','consistencia'],true,1),
('alim_01','alimentacao',1,2,'Uma refeição sem pressa','Em uma refeição de hoje, sente-se e tente comer sem fazer outra atividade ao mesmo tempo.',array['alimentacao','rotina'],true,1),
('alim_02','alimentacao',1,3,'Inclua algo natural','Acrescente uma fruta, verdura ou legume em uma refeição que você já faria normalmente.',array['alimentacao','energia'],true,1),
('alim_03','alimentacao',2,5,'Antecipe uma escolha','Decida com antecedência uma refeição ou lanche de hoje para reduzir decisões no improviso.',array['alimentacao','rotina','consistencia'],true,1),
('alim_04','alimentacao',2,5,'Observe a fome','Antes de uma refeição, pare por alguns segundos e perceba como está sua fome. Registre em uma frase.',array['alimentacao','consistencia'],true,1),
('alim_05','alimentacao',3,10,'Prepare o próximo passo','Deixe encaminhada uma opção simples para sua próxima refeição ou lanche.',array['alimentacao','rotina'],true,1),
('mov_01','movimento',1,3,'Três minutos em movimento','Faça três minutos de movimento leve que seja confortável para você.',array['movimento','energia','consistencia'],true,1),
('mov_02','movimento',1,5,'Caminhada curta','Faça uma caminhada curta em ritmo confortável, dentro ou fora de casa.',array['movimento','energia'],true,1),
('mov_03','movimento',2,8,'Pausa ativa','Separe alguns minutos para se levantar, caminhar um pouco e mudar de posição.',array['movimento','energia','rotina'],true,1),
('mov_04','movimento',2,10,'Dez minutos intencionais','Reserve até dez minutos para uma atividade física que você já sabe que pode fazer com segurança.',array['movimento','consistencia'],true,1),
('mov_05','movimento',3,15,'Bloco de movimento','Planeje e faça um bloco de até quinze minutos de uma atividade adequada à sua rotina.',array['movimento','energia'],true,1),
('sono_01','sono',1,2,'Prepare o amanhã','Antes de dormir, deixe separado algo que reduza correria na manhã seguinte.',array['rotina','energia'],true,1),
('sono_02','sono',1,3,'Desacelere por três minutos','Faça três minutos de transição antes de dormir, com menos estímulos e sem outra tarefa ao mesmo tempo.',array['energia','rotina'],true,1),
('sono_03','sono',2,5,'Horário de desacelerar','Escolha um horário aproximado para começar a encerrar o dia e coloque um lembrete.',array['rotina','consistencia','energia'],true,1),
('sono_04','sono',3,10,'Ritual curto de encerramento','Monte uma sequência simples de 2 ou 3 ações para sinalizar que seu dia está terminando.',array['rotina','consistencia'],true,1),
('plan_01','planejamento',1,2,'Uma prioridade','Escolha uma única coisa que você quer garantir hoje e escreva em uma frase.',array['rotina','consistencia'],true,1),
('plan_02','planejamento',1,3,'Facilite o hábito','Mude uma coisa no ambiente para tornar um hábito desejado mais fácil de executar.',array['rotina','consistencia'],true,1),
('plan_03','planejamento',2,5,'Plano se-então','Complete: “Se meu dia sair do planejado, então eu ainda consigo fazer...” e escolha uma versão mínima do hábito.',array['consistencia','rotina'],true,1),
('plan_04','planejamento',3,10,'Prepare dois atalhos','Identifique dois pontos da rotina que costumam atrapalhar e deixe uma solução simples preparada para cada um.',array['consistencia','rotina'],true,1),
('mente_01','mente',1,2,'Registre uma vitória','Escreva uma coisa pequena que você fez bem hoje, mesmo que o restante do dia não tenha saído como queria.',array['consistencia','energia'],true,1),
('mente_02','mente',1,3,'Pausa sem cobrança','Faça uma pausa curta e perceba como você está, sem transformar isso em avaliação de desempenho.',array['energia','consistencia'],true,1),
('mente_03','mente',2,5,'Fechamento do dia','Em três frases, registre: o que funcionou, o que atrapalhou e o que você quer repetir amanhã.',array['consistencia','rotina'],true,1),
('mente_04','mente',3,8,'Revisão de padrão','Olhe os últimos dias e identifique um hábito que ficou mais fácil e um que ainda precisa ser simplificado.',array['consistencia','rotina'],true,1)
on conflict (id) do update set
  category=excluded.category,
  level=excluded.level,
  minutes=excluded.minutes,
  title=excluded.title,
  body=excluded.body,
  goal_tags=excluded.goal_tags,
  active=excluded.active,
  approved_version=excluded.approved_version,
  updated_at=now();
