from pathlib import Path

path = Path('assets/motor-flow-v2.js')
text = path.read_text(encoding='utf-8')
marker = '/* MOTOR_ORDER_AI_V1 */'

if marker in text:
    raise SystemExit('MOTOR ORDER AI patch already applied')

block = r'''

/* MOTOR_ORDER_AI_V1 */
(()=>{
const ORDER_AI_API='https://ym-raiox-backend.vercel.app/api/motor/ordenar-ia';
const state=new Map();
const style=document.createElement('style');style.id='ymMotorOrderAiStyles';style.textContent=`
.order-ai{margin:0 0 12px;border:1px solid #cddaf0;background:linear-gradient(135deg,#f8fbff,#fff);border-radius:14px;overflow:hidden}.order-ai-head{display:flex;justify-content:space-between;gap:10px;align-items:flex-start;padding:13px 14px;background:#eef4ff;border-bottom:1px solid #d8e4f6}.order-ai-head b{display:block;font:800 11px Montserrat;color:#0a2540}.order-ai-head span{display:block;font-size:9px;line-height:1.45;color:#587087;margin-top:3px}.order-ai-body{padding:13px 14px}.order-ai-note{font-size:9.5px;line-height:1.55;color:#4b647a;background:#f7f9fc;border:1px solid #e0e7ef;border-radius:10px;padding:9px 10px}.order-ai-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:9px}.order-ai-manual{margin-top:10px;padding-top:10px;border-top:1px solid #e3eaf2}.order-ai-results{display:grid;gap:9px;margin-top:12px}.order-ai-card{background:#fff;border:1px solid #dce5ef;border-radius:12px;padding:11px}.order-ai-card h4{font:800 11px Montserrat;color:#0a2540;margin:0 0 6px}.order-ai-card p{font-size:9.5px;line-height:1.55;color:#425d73;margin:5px 0}.order-ai-basis{background:#f5f2ff;border-left:3px solid #484dcf;border-radius:8px;padding:8px 9px;margin-top:7px}.order-ai-basis b{display:block;font-size:8.5px;color:#484dcf;margin-bottom:3px}.order-ai-basis span{font-size:9px;line-height:1.5;color:#4e5c75}.order-ai-meta{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:8px}.order-ai-meta>div{background:#f8fafc;border-radius:8px;padding:8px}.order-ai-meta b{display:block;font-size:8.2px;color:#0a2540;margin-bottom:3px}.order-ai-meta span{font-size:8.7px;line-height:1.4;color:#607487}.order-ai-loading{padding:12px;border:1px dashed #b7c7dc;border-radius:10px;background:#f8fbff;font-size:9.5px;color:#50677d;margin-top:10px}.order-ai-imported{font-size:8.5px;font-weight:800;color:#238a68;margin-top:8px}.order-ai .ym-textarea{min-height:84px}@media(max-width:700px){.order-ai-head{flex-direction:column}.order-ai-meta{grid-template-columns:1fr}.order-ai-actions .ym-btn{width:100%}}
`;document.head.appendChild(style);
const E=v=>YM.esc(v??'');
function gateApproved(){const g=(bundle?.gates||[]).find(x=>x.gate_code==='VER_GATE')||(bundle?.gates||[])[0];return g?.status==='APROVADO'}
function renderSuggestion(s,st){const imported=!!st.imported?.[s.id];return `<div class="order-ai-card"><div class="ym-meta">SUGESTÃO DA IA · NÃO PRIORIZADA</div><h4>${E(s.action)}</h4><p><b>Por que pode ajudar:</b> ${E(s.rationale)}</p><p><b>Impacto esperado no destino:</b> ${E(s.impact_on_destination)}</p><div class="order-ai-basis"><b>BASE NO VER VALIDADO</b><span>${E(s.ver_basis)}</span></div><div class="order-ai-meta"><div><b>DEPENDÊNCIA</b><span>${E(s.dependency||'Nenhuma dependência específica indicada.')}</span></div><div><b>CRITÉRIO DE SUCESSO</b><span>${E(s.success_criterion||'Definir na validação humana.')}</span></div>${s.execution_capacity?`<div><b>CAPACIDADE / EXECUÇÃO</b><span>${E(s.execution_capacity)}</span></div>`:''}${s.risk_of_delay?`<div><b>RISCO DE ADIAR</b><span>${E(s.risk_of_delay)}</span></div>`:''}</div>${imported?'<div class="order-ai-imported">✓ Já levada para validação humana</div>':`<div class="order-ai-actions"><button class="ym-btn ok" onclick="acceptOrderAISuggestion('${E(s.id)}',false)">Levar para validação</button><button class="ym-btn secondary" onclick="acceptOrderAISuggestion('${E(s.id)}',true)">Guardar como “não agora”</button></div>`}</div>`}
function html(){const st=state.get(currentId)||{};return `<div class="order-ai" data-order-ai><div class="order-ai-head"><div><b>IA → SUGESTÕES DE AÇÃO</b><span>O VER já foi validado. Agora a IA transforma as conclusões humanas em ações candidatas para você avaliar.</span></div><span>${st.model?E(st.model):'A IA sugere · o humano decide'}</span></div><div class="order-ai-body"><div class="order-ai-note"><b>Regra desta etapa:</b> a IA não define prioridade, sequência, prazo ou responsável. Ela apenas propõe caminhos com base no VER validado. Você decide o que entra no ORDENAR.</div><div class="order-ai-actions"><button class="ym-btn" onclick="generateOrderAI(false)" ${st.loading?'disabled':''}>${st.loading?'Analisando…':'Análise automática'}</button></div><div class="order-ai-manual"><label class="ym-label">Prompt manual para orientar a IA (opcional)</label><textarea id="orderAiPrompt" class="ym-textarea" placeholder="Ex.: Sugira ações de curto prazo que não dependam de mídia paga. Não altere o diagnóstico do VER.">${E(st.prompt||'')}</textarea><div class="order-ai-actions"><button class="ym-btn secondary" onclick="generateOrderAI(true)" ${st.loading?'disabled':''}>Analisar com este prompt</button></div></div>${st.loading?'<div class="order-ai-loading">A IA está lendo as conclusões, evidências, métricas e contexto operacional do VER validado…</div>':''}${st.error?`<div class="order-ai-loading" style="border-color:#e4bcbc;background:#fff7f7;color:#8a3434">${E(st.error)}</div>`:''}${st.suggestions?.length?`<div class="order-ai-results">${st.suggestions.map(s=>renderSuggestion(s,st)).join('')}</div>`:''}</div></div>`}
function decorate(){if(!bundle||!currentId||!gateApproved())return;const body=document.querySelector('.sec-order > .body');if(!body)return;body.querySelector('[data-order-ai]')?.remove();body.insertAdjacentHTML('afterbegin',html())}
async function callAI(manual){const st=state.get(currentId)||{};const prompt=document.getElementById('orderAiPrompt')?.value?.trim()||'';if(manual&&!prompt)return YM.toast('Escreva a orientação manual para a IA.',true);st.loading=true;st.error='';st.prompt=prompt;state.set(currentId,st);decorate();try{const s=await YM.requireSession('/MOTOR'+location.search);if(!s)throw new Error('Sessão necessária');const r=await fetch(ORDER_AI_API,{method:'POST',headers:{Authorization:'Bearer '+s.access_token,'Content-Type':'application/json'},body:JSON.stringify({case_id:currentId,manual_prompt:manual?prompt:''})});const j=await r.json().catch(()=>({}));if(!r.ok){const labels={ver_gate_not_approved:'Aprove o Gate VER antes de gerar ações.',human_conclusion_required:'O VER precisa ter uma conclusão humana registrada.',ai_provider_failed:'A IA está temporariamente indisponível.',ai_empty_suggestions:'A IA não encontrou sugestões utilizáveis neste VER.'};throw new Error(labels[j.error]||j.error||'Falha na geração das ações')}st.loading=false;st.suggestions=j.suggestions||[];st.model=j.model||'IA';st.provider=j.provider||'';st.error='';st.imported=st.imported||{};state.set(currentId,st);decorate();YM.toast(`${st.suggestions.length} sugestão(ões) gerada(s). Agora valide humanamente.`)}catch(e){st.loading=false;st.error=e.message||String(e);state.set(currentId,st);decorate();YM.toast(st.error,true)}}
window.generateOrderAI=manual=>callAI(!!manual);
window.acceptOrderAISuggestion=async(id,notNow)=>{const st=state.get(currentId)||{},s=(st.suggestions||[]).find(x=>String(x.id)===String(id));if(!s)return;try{const rationale=`${s.rationale}${s.ver_basis?`\n\nBase no VER validado: ${s.ver_basis}`:''}`;await authFetch('motor-order-actions','POST',{case_id:currentId,action:'CREATE_CANDIDATE',candidate_action:s.action,rationale,impact_on_destination:s.impact_on_destination,dependency:s.dependency||'',execution_capacity:s.execution_capacity||'',risk_of_delay:s.risk_of_delay||'',digital_front:s.digital_front||'',success_criterion:s.success_criterion||'',not_now:!!notNow});st.imported=st.imported||{};st.imported[s.id]=true;state.set(currentId,st);YM.toast(notNow?'Sugestão registrada como “não agora”.':'Sugestão levada para validação humana.');await openCase(currentId);await loadDashboard()}catch(e){YM.toast(e.message||String(e),true)}};
const baseOpenOrderAI=openCase;openCase=async function(id){await baseOpenOrderAI(id);decorate()};window.openCase=openCase;
setTimeout(decorate,250);
})();
'''

path.write_text(text + block, encoding='utf-8')
print('patched assets/motor-flow-v2.js')
