plugins {
    id 'com.android.application'
}

android {
    namespace 'br.com.ymnegocios.desafiodocasal'
    compileSdk 36

    defaultConfig {
        applicationId 'br.com.ymnegocios.desafiodocasal'
        minSdk 26
        targetSdk 36
        versionCode 4
        versionName '1.0.3'
    }

    buildTypes {
        debug {
            applicationIdSuffix '.debug'
            versionNameSuffix '-debug'
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
